---
apiVersion: v1
kind: Namespace
metadata:
  name: swiss-army-knife
  labels:
    app: swiss-army-knife
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: swiss-army-knife
  name: swiss-army-knife
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: swiss-army-knife
  namespace: swiss-army-knife
  labels:
    app: swiss-army-knife
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: swiss-army-knife
  name: swiss-army-knife
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: swiss-army-knife
subjects:
  - kind: ServiceAccount
    name: swiss-army-knife
    namespace: swiss-army-knife
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: swiss-army-knife
  namespace: swiss-army-knife
  labels:
    app: swiss-army-knife
spec:
  selector:
    matchLabels:
      app: swiss-army-knife
  template:
    metadata:
      labels:
        app: swiss-army-knife
    spec:
      tolerations:
        - operator: Exists
      containers:
        - name: swiss-army-knife
          image: supporttools/swiss-army-knife
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
      serviceAccountName: swiss-army-knife
      volumes:
        - name: rootfs
          hostPath:
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: swiss-army-knife
  namespace: swiss-army-knife
  labels:
    app: swiss-army-knife
spec:
  selector:
    name: swiss-army-knife
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP